platform :ios,'8.2.1'
target 'CabbageNet' do

pod 'JPush'
pod 'MBProgressHUD'
pod 'AFNetworking'
pod 'SDWebImage'
pod 'MJRefresh'
pod 'MJExtension'
pod 'Masonry'
pod 'IQKeyboardManager'
pod 'FMDB'


end
